#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  install.sh  —  One-shot system-wide setup for the Biometric Server     ║
# ║  Raspberry Pi OS Bookworm (Debian 12)  ·  64-bit  ·  Python 3.11       ║
# ║                                                                          ║
# ║  WHY NOT A VENV?                                                         ║
# ║  ─────────────────────────────────────────────────────────────────────  ║
# ║  picamera2 and libcamera are Debian packages that only work with the    ║
# ║  system Python interpreter.  They cannot be bundled into a venv or a   ║
# ║  standalone executable.  Installing everything into the system Python  ║
# ║  with --break-system-packages is the officially recommended approach    ║
# ║  for a dedicated Raspberry Pi running a single project.                 ║
# ║                                                                          ║
# ║  The "externally managed environment" error you saw was Debian 12's    ║
# ║  PEP-668 enforcement.  This flag bypasses it permanently — perfectly   ║
# ║  safe on a Pi dedicated to this project.                                ║
# ║                                                                          ║
# ║  Usage:                                                                  ║
# ║    chmod +x install.sh && sudo ./install.sh                             ║
# ╚══════════════════════════════════════════════════════════════════════════╝

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✅  $*${NC}"; }
info() { echo -e "${YELLOW}ℹ   $*${NC}"; }
die()  { echo -e "${RED}❌  $*${NC}"; exit 1; }

# ── Must run as root ──────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run as root: sudo ./install.sh"

# ── Detect Raspberry Pi OS Bookworm (required) ────────────────────────────────
if ! grep -q "bookworm\|Bookworm" /etc/os-release 2>/dev/null; then
    info "OS is not Bookworm — script may still work but is untested."
fi

PYTHON=python3
PY_VER=$($PYTHON --version 2>&1)
info "Using $PY_VER at $($PYTHON -c 'import sys; print(sys.executable)')"

# ── 1. System packages (apt) ──────────────────────────────────────────────────
# picamera2, libcamera, and kms++ MUST come from apt — they are C extensions
# that link against system libcamera.so and cannot be pip-installed.
info "Installing system packages via apt…"
apt-get update -qq
apt-get install -y --no-install-recommends \
    python3-picamera2 \
    python3-libcamera \
    python3-kms++ \
    python3-pip \
    python3-dev \
    libcap-dev \
    libatlas-base-dev \
    libjpeg-dev \
    libopenblas-dev \
    fonts-dejavu \
    git \
    curl
ok "System packages installed."

# ── 2. Python packages via pip (system-wide, --break-system-packages) ─────────
# The --break-system-packages flag is necessary on Bookworm (PEP-668).
# It is safe here because this Pi is a dedicated appliance.
info "Installing Python packages into system Python…"

BSP="--break-system-packages --quiet"

# NumPy pinned below 2.0 — onnxruntime and mediapipe require <2.0 on aarch64
$PYTHON -m pip install $BSP "numpy>=1.24.0,<2.0.0"

# OpenCV
$PYTHON -m pip install $BSP "opencv-python>=4.8.0"

# Pillow
$PYTHON -m pip install $BSP "Pillow>=10.0.0"

# Adafruit TFT display drivers
$PYTHON -m pip install $BSP adafruit-blinka adafruit-circuitpython-rgb-display

# MediaPipe (Google ARM64 wheel — downloads automatically on aarch64 Bookworm)
$PYTHON -m pip install $BSP mediapipe

# ONNX Runtime (aarch64 wheel)
$PYTHON -m pip install $BSP onnxruntime

# Audio / serial
$PYTHON -m pip install $BSP pyserial psutil

# WebSocket + mDNS
$PYTHON -m pip install $BSP websockets "zeroconf>=0.39"

# Textual TUI (for client.py)
$PYTHON -m pip install $BSP textual

ok "Python packages installed."

# ── 3. Verify critical imports ────────────────────────────────────────────────
info "Verifying imports…"
$PYTHON - <<'PYCHECK'
import sys
failures = []
for pkg in ["picamera2", "cv2", "numpy", "mediapipe",
            "PIL", "board", "adafruit_rgb_display",
            "websockets", "zeroconf", "onnxruntime", "serial"]:
    try:
        __import__(pkg)
        print(f"  ✓  {pkg}")
    except ImportError as e:
        print(f"  ✗  {pkg}  ({e})")
        failures.append(pkg)
if failures:
    print(f"\n⚠️  Failed imports: {failures}")
    print("   These may need manual intervention (check apt / pip output above).")
    sys.exit(1)
else:
    print("\n✅  All imports OK.")
PYCHECK

ok "Verification passed."

# ── 4. Create run script ──────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cat > "$SCRIPT_DIR/run_server.sh" <<RUNSCRIPT
#!/usr/bin/env bash
# Auto-generated by install.sh
# Run this to start the biometric server — no venv activation needed.
cd "$SCRIPT_DIR"
exec $PYTHON server.py "\$@"
RUNSCRIPT
chmod +x "$SCRIPT_DIR/run_server.sh"
ok "Created run_server.sh"

# ── 5. Systemd service (optional — uncomment to enable on-boot autostart) ─────
# Uncomment the block below to install as a systemd service that starts
# automatically on every boot.
#
# SERVICE_FILE=/etc/systemd/system/biometric.service
# cat > "$SERVICE_FILE" <<SERVICE
# [Unit]
# Description=Biometric Authentication Server
# After=network-online.target
# Wants=network-online.target
#
# [Service]
# WorkingDirectory=$SCRIPT_DIR
# ExecStart=$PYTHON $SCRIPT_DIR/server.py
# Restart=always
# RestartSec=5
# StandardOutput=journal
# StandardError=journal
#
# [Install]
# WantedBy=multi-user.target
# SERVICE
# systemctl daemon-reload
# systemctl enable biometric.service
# systemctl start  biometric.service
# ok "Systemd service installed and started."

echo ""
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Installation complete.                       ${NC}"
echo -e "${GREEN}  Start server:  ./run_server.sh               ${NC}"
echo -e "${GREEN}  Or directly:   python3 server.py             ${NC}"
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
